# Site settings
title: Cambridge Water Polo 
description: Cambridge Water Polo Club
author: Tyler Lee
baseurl: ""
url: ""

permalink: /:title
include: ['_pages']

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

exclude:
  - README.md
  - LICENSE
